apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      name: account-service
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: datpm/account-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config-map
            - secretRef:
                name: secret-config
      restartPolicy: Always
      