apiVersion: v1
kind: Service
metadata:
  name: account-service-dev
spec:
  selector:
    app: account-service-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
  